version: "1"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql
    ports:
      - "30000:3306"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_USER: pav
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pav
    volumes:
      - ./db:/docker-entrypoint-initdb.d